### ISSUE TITLE
Release 2020.3.4

### ISSUE THREAD

**Issue by adombeck** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#78]
The bugfix release 2020.3.4 is not available via flatpak:

```
flatpak remote-info --log flathub com.jetbrains.IntelliJ-IDEA-Ultimate

        ID: com.jetbrains.IntelliJ-IDEA-Ultimate
       Ref: app/com.jetbrains.IntelliJ-IDEA-Ultimate/x86_64/stable
      Arch: x86_64
    Branch: x86_64
Collection: org.flathub.Stable
  Download: 215.7 kB
 Installed: 565.2 kB
   Runtime: org.freedesktop.Sdk/x86_64/20.08
       Sdk: org.freedesktop.Sdk/x86_64/20.08

    Commit: c11ecf62091ee1e38ad3a8bffe0b97d53f43bdae9c939f9edff14fecb10b1f7e
    Parent: 98e65d0f4fb1689624709780b9ca61610411d0d8000e17a67c6cd3a67702d5c7
   Subject: fix: update idea-iu hash for release 2021.1.3 (5ee6b7b8)
      Date: 2021-06-30 21:23:25 +0000
   History: 

    Commit: 98e65d0f4fb1689624709780b9ca61610411d0d8000e17a67c6cd3a67702d5c7
   Subject: update idea-iu to 2021.1.3 (774ef4e8)
      Date: 2021-06-29 17:50:16 +0000

    Commit: 36668810a6e42d745228d2f3a6e325c70060c770f4787ac511c269b393aa6be1
   Subject: feat: add support for discord integration (14a6d80d)
      Date: 2021-06-20 12:43:16 +0000

    Commit: 48834ade1ef52c0273cf51d66743c3d27a189944a4bb698dd3d2ac4d65a1067a
   Subject: update intellij idea ultimate to to 2021.1.2 (ffda5d8d)
      Date: 2021-06-01 21:40:15 +0000

    Commit: fb1caca69afd4cf61e0991634d0c9c69bfec453a7094849bf7c1c5b1450d3f86
   Subject: Update ideaIU.tar.gz to 2021.1.1 (8f97834e)
      Date: 2021-04-30 17:13:48 +0000

    Commit: f6bcee8fd7c478d4e4146043d009b88a9f58d173ad603946f5f9c17e5c245736
   Subject: flathub bot forget update release version (352e77fb)
      Date: 2021-04-08 01:44:15 +0000

    Commit: 0563753dcc771309af7aec528f800440df532b074b86c4a630b6aa1fe0643986
   Subject: Update ideaIU.tar.gz to 2021.1 (7b47fa02)
      Date: 2021-04-07 11:59:35 +0000

    Commit: cee8f85e765b507f8b79dd7c1309671d61b96772bfa3098c6adc1cd4b4979ee4
   Subject: Update ideaIU.tar.gz to 2020.3.3 (df0e7c2d)
      Date: 2021-03-16 14:52:44 +0000

    Commit: df2b8f0f442362828ff27d5f0f01696f2dca3ad3c77749634ac939e0b086e530
   Subject: intellij idea ultimate edition release 2020.3.2 (de758850)
      Date: 2021-01-26 14:41:08 +0000

    Commit: 2da2fe8a0ec6cf61bb7a735857567eadb9b4cf21ffd3f4494716ba7f7708109f
   Subject: intellij idea ultimate edition release 2020.3.1 (3e2bd575)
      Date: 2020-12-30 13:40:46 +0000

    Commit: 38ce13dbe1bd72bc5f01c1c62df0f7b89f4b4774e0a990d9aae453b4e439157c
   Subject: intellij idea ultimate edition release 2020.3 (26f45f7f)
      Date: 2020-12-01 17:54:21 +0000

    Commit: 6cf5fd3652591971afefe5a00f3bc75fc08a252d516eb086862d0804c7f7ae92
   Subject: intellij idea ultimate edition release 2020.2.4 (38246a1d)
      Date: 2020-11-25 14:38:25 +0000

    Commit: 0bed4b7d7a3984451c01ea0498104eec7b025254fb1532375eb6b01c98a0c94b
   Subject: refactor: convert manifest to yaml (46d55439)
      Date: 2020-10-26 21:28:21 +0000

    Commit: 468cc8c48737bdbea748f25052b21d12d871792a5889bc4f160d53315dfd20a0
   Subject: intellij idea ultimate edition release 2020.2.3 (f7fc67cd)
      Date: 2020-10-06 14:33:36 +0000

    Commit: e6ab6499c9af5d6c8b4dde4e4315e49d72e6816e0974a725afedacfb07c85573
   Subject: intellij idea ultimate edition release 2020.2.2 (4620f80e)
      Date: 2020-09-15 17:35:57 +0000

    Commit: 649f478b240e5b87a44b1ecfa33dd60782c011a9013d7807d48bd260cb03c42d
   Subject: feat: upgrade freedesktop runtime version to 20.08 (a3250c65)
      Date: 2020-09-01 14:51:07 +0000
```
